# Generated by Django 5.2.6 on 2025-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('viewer', 'Viewer')], db_index=True, default='staff', help_text='Coarse-grained role. Order of privilege (low→high): viewer < staff < accountant < manager < admin.', max_length=20),
        ),
    ]
