# Generated by Django 5.2.6 on 2025-09-05 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Optional invoice number', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initially created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='sales.customer')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AR Invoice',
                'verbose_name_plural': 'AR Invoices',
            },
        ),
        migrations.CreateModel(
            name='ARPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='OTHER', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initially created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='sales.customer')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AR Payment',
                'verbose_name_plural': 'AR Payments',
            },
        ),
        migrations.CreateModel(
            name='ARPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='allocations', to='accounting.arinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.arpayment')),
            ],
        ),
        migrations.AddIndex(
            model_name='arinvoice',
            index=models.Index(fields=['customer', 'status'], name='accounting__custome_14db28_idx'),
        ),
        migrations.AddIndex(
            model_name='arinvoice',
            index=models.Index(fields=['invoice_date'], name='accounting__invoice_4091af_idx'),
        ),
        migrations.AddIndex(
            model_name='arpayment',
            index=models.Index(fields=['customer', 'paid_at'], name='accounting__custome_8d4156_idx'),
        ),
        migrations.AddIndex(
            model_name='arpaymentallocation',
            index=models.Index(fields=['invoice'], name='accounting__invoice_beab4a_idx'),
        ),
        migrations.AddIndex(
            model_name='arpaymentallocation',
            index=models.Index(fields=['payment'], name='accounting__payment_973f77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='arpaymentallocation',
            unique_together={('payment', 'invoice')},
        ),
    ]
