# Generated by Django 5.2.6 on 2025-09-05 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_invoice_invoiceline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
